import { Inter } from "next/font/google"; // Importing the Inter font from the Google Fonts API
import "./globals.css"; // Importing global styles from globals.css file
import { AuthProvider } from "./Providers"; // Importing the AuthProvider from Providers file

const inter = Inter({ subsets: ["latin"] }); // Initializing the Inter font with Latin subset

export const metadata = { // Defining metadata for the application
  title: "Next Auth App", // Title of the application
  description: "Generated by create next app", // Description of the application
};

export default function RootLayout({ children }) { // Defining a functional component named RootLayout that takes children as parameter
  return (
    <html lang="en"> {/* Setting the language of the HTML document */}
      <body className={inter.className}> {/* Applying Inter font to the body */}
        <main className="h-screen bg-slate-400">
          <AuthProvider>{children}</AuthProvider> {/* Wrapping children with AuthProvider */}
        </main>
      </body>
    </html>
  );
}
